# Generated by Django 3.0.2 on 2020-01-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(default='', max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('gender', models.CharField(max_length=20)),
                ('user_type', models.CharField(max_length=20)),
            ],
        ),
    ]
