# Generated by Django 3.2.3 on 2021-06-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_login_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
