# Generated by Django 3.2.3 on 2021-06-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210628_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='email',
            new_name='email1',
        ),
    ]
